#!/usr/bin/env python
import sys, os
"""
CPG --			showcpg -h
				showcpg
				showcpg -d
				showcpg -space
				showcpg -r
				showcpg -sag
				showcpg -sdg
				showcpg -alert
				showcpg -alerttime
"""

#args = len(sys.argv)
#command = sys.argv[0].split("/")[-1]

commands=["showcpg -h","showcpg", "showcpg -d","showcpg -space", "showcpg -r","showcpg -sag","showcpg -sdg","showcpg -alert","showcpg -alerttime"]
for command in commands:
        


if args == 1:
    #no arguments
    path = os.path.join(os.getcwd(),"CONF",command)
    with open(path) as f:
        print f.read()
else:
    filename = command+"".join(sys.argv[1:])
    path = os.path.join(os.getcwd(), "CONF",filename)
    argument = sys.argv[1]
    try:
        with open(path) as f:
            print f.read()
    except:
        raise

    """
    if argument == '-d':
         with f as open(path):
            print f.read()
         print "showcpg -d", "".join(sys.args)
    elif argument == '-h':
         with f as open(path):
            print f.read()
         print "showcpg -h"
    elif argument == '-space':
         with f as open(path):
            print f.read()
         print "showcpg -space"
    elif argument == '-r':
         with f as open(path):
            print f.read()
         print "showcpg -r"
    elif argument == '-sdg':
         with f as open(path):
            print f.read()
         print "showcpg -sdg"
    elif argument == '-alert':
         with f as open(path):
            print f.read()
         print "showcpg -alert"
    elif argument == '-alerttime':
         print "showcpg -alerttime"

    """
