#!/usr/bin/env python
"""
VLun --         showvlun -showcols 
				showvlun -lvw
				showvlun -pathsum
				showvlun -a
				showvlun -t
				showvlun -host *
				showvlun -v *
				showvlun -l *
				showvlun -nodes 1
				showvlun -nodes 0,1
				showvlun -slots *
				showvlun -ports 0
				showvlun -domain *
"""
import sys, os

args = len(sys.argv)
command = sys.argv[0].split("/")[-1]

if args == 1:
    path = os.path.join(os.sep,"root","HPE3PAR","CONF","VLun",command)
    with open(path) as f:
        print f.read()
else:
    filename = command+"".join(sys.argv[1:])
    path = os.path.join(os.sep,"root","HPE3PAR","CONF","VLun",filename)
    argument = sys.argv[1]
    try:
        with open(path) as f:
            print f.read()
    except:
        raise

