#!/usr/bin/env python
"""
Physical Drive --
                showpd
                                showpd -i
                                showpd -e
                                showpd -c
                                showpd -state
                                showpd  -s
                                showpd -path
                                showpd -w
                                showpd -nodes 0
                                showpd -showcols
                                showpd -space
"""
import sys, os

args = len(sys.argv)
command = sys.argv[0].split("/")[-1]

if args == 1:
    path = os.path.join(os.sep,"root","HPE3PAR","CONF","PhysicalDrive",command)
    with open(path) as f:
        print f.read()
else:
    filename = command+"".join(sys.argv[1:])
    path = os.path.join(os.sep,"root","HPE3PAR","CONF","PhysicalDrive",filename)
    argument = sys.argv[1]
    try:
        with open(path) as f:
            print f.read()
    except:
        raise
