#!/usr/bin/env python
"""
PORT --
                showport
                                showport -i
                                showport -c
                                showport -rc
                                showport -rcfc
                                showport -rcip
                                showport -iscsi
                                showport -fcoe
                                showport -sfp
                                showport -d -sfp
                                showport -failed
                                showport -state
                                showport -ids
                                showport -fs

"""
import sys, os

args = len(sys.argv)
command = sys.argv[0].split("/")[-1]

if args == 1:
    path = os.path.join(os.sep,"root","HPE3PAR","CONF","Port",command)
    with open(path) as f:
        print f.read()
else:
    filename = command+"".join(sys.argv[1:])
    path = os.path.join(os.sep,"root","HPE3PAR","CONF","Port",filename)
    argument = sys.argv[1]
    try:
        with open(path) as f:
            print f.read()
    except:
        raise
