#!/usr/bin/env python
import sys, os
"""
CPG --			showcpg -h
				showcpg
				showcpg -d
				showcpg -space
				showcpg -r
				showcpg -sag
				showcpg -sdg
				showcpg -alert
				showcpg -alerttime
"""

args = len(sys.argv)
command = sys.argv[0].split("/")[-1]

if args == 1:
    #no arguments
    path = os.path.join(os.getcwd(),"CONF","CPG",command)
    with open(path) as f:
        print f.read()
else:
    filename = command+"".join(sys.argv[1:])
    path = os.path.join(os.getcwd(), "CONF","CPG",filename)
    argument = sys.argv[1]
    try:
        with open(path) as f:
            print f.read()
    except:
        raise

