#!/usr/bin/env python
import sys, os
"""
controller - 
             idPerf -    srstatld -attime -groupby NODE
CPG  -
	srstatld  - attime -groupby CPG_NAME
Logical Drive - 
	idperf  -  srstatld -attime -groupby LD_NAME

system -
       	Idperf -          srstatld -btsecs -15m
	Idspace -         srstatld -attime -groupby nODE
"""
arglen = len(sys.argv)
args = sys.argv[1:]
command = 'ldPerf.txt' 

if arglen == 1:
    #no arguments
    print "Not a valid command"
else:
    if 'NODE' in args:
        path = os.path.join(os.sep,"root","HPE3PAR","PERF","controller",command)
    elif 'CPG_NAME' in args:
        path = os.path.join(os.sep,"root","HPE3PAR","PERF","CPG",command)
    elif 'LD_NAME' in args:
        path = os.path.join(os.sep,"root","HPE3PAR","PERF","LogicalDrive",command)
    elif 'nODE' in args or '-btsecs' in args:
        path = os.path.join(os.sep,"root","HPE3PAR","PERF","system",command)
    try:
        with open(path) as f:
            print f.read()
    except:
        raise

