#!/usr/bin/env python
import sys, os
"""
Host -vlunPerf - srstatvlun -attime -groupby HOST_NAME

StoragePort -
              vlunperf  -     srstatvlun -attime -groupby PORT_P
vistualvolume -
            vlunperf -        srstatvlun -attime -groupby VV_NAME
vlun - 			
		    vlunperf -        srstatvlun -attime -groupby LUN

"""

arglen = len(sys.argv)
args = sys.argv[1:]
command = 'vlunPerf.txt' 


if arglen == 1:
    #no arguments
    print "Not a valid command"
else:
    if 'HOST_NAME' in args:
        path = os.path.join(os.sep,"root","HPE3PAR","PERF","Host",command)
    elif 'PORT_P' in args:
        path = os.path.join(os.sep,"root","HPE3PAR","PERF","StoragePort",command)
    elif 'VV_NAME' in args:
        path = os.path.join(os.sep,"root","HPE3PAR","PERF","virtualVolume",command)
    elif 'LUN' in args:
        path = os.path.join(os.sep,"root","HPE3PAR","PERF","vlun",command)
    try:
        with open(path) as f:
            print f.read()
    except:
        raise

