#!/usr/bin/env python
import sys, os
"""
Physical Drive - diskperf -   srstatpd -attime -groupby PDID
system -
			diskperf -        srstatpd -btsecs -15m
"""

arglen = len(sys.argv)
args = sys.argv[1:]
command = 'diskPerf.txt' 


if arglen == 1:
    #no arguments
    print "Not a valid command"
else:
    if 'PDID' in args:
        path = os.path.join(os.sep,"root","HPE3PAR","PERF","physicalDrive",command)
    elif '-btsecs' in args:
        path = os.path.join(os.sep,"root","HPE3PAR","PERF","system",command)
    try:
        with open(path) as f:
            print f.read()
    except:
        raise

