#!/usr/bin/env python
import sys, os
"""
system -
                 vvspace -         srvvspace -btsecs -15m
vistualvolume -
	         vvspace -         srvvspace -attime -groupby VV_NAME

"""
arglen = len(sys.argv)
args = sys.argv[1:]
command = 'diskSpace.txt' 

if arglen == 1:
    #no arguments
    print "Not a valid command"
else:
    if 'VV_NAME' in args:
        path = os.path.join(os.sep,"root","HPE3PAR","PERF","virtualVolume",command)
    elif '-btsecs' in args:
        path = os.path.join(os.sep,"root","HPE3PAR","PERF","system",command)
    try:
        with open(path) as f:
            print f.read()
    except:
        raise

