#!/usr/bin/env python

import sys,os,time
from random import randint

#time.sleep(randint(0,10))
time.sleep(2)

if not (len(sys.argv) > 1):
   sys.exit(0) 
file='_'.join(sys.argv)
if "," in file:
    for each in file.split(","):
        dump_file = os.path.join(os.sep,"root","CiscoSANSwitch",each)
        if os.path.exists(dump_file):
           with open(dump_file) as f:
              print f.read()
else:
    dump_file = os.path.join(os.sep,"root","CiscoSANSwitch",file)
    if os.path.exists(dump_file):
        with open(dump_file) as f:
           print f.read() 
