#!/usr/bin/env python
"""
HOSTSET --
                showhostset
                                showhostset
                                showhostset -d

"""
import sys, os

args = len(sys.argv)
command = sys.argv[0].split("/")[-1]

if args == 1:
    path = os.path.join(os.sep,"root","HPE3PAR","CONF","HostSet",command)
    with open(path) as f:
        print f.read()
else:
    filename = command+"".join(sys.argv[1:])
    path = os.path.join(os.sep,"root","HPE3PAR","CONF","HostSet",filename)
    argument = sys.argv[1]
    try:
        with open(path) as f:
            print f.read()
    except:
        raise

