#!/usr/bin/env python
import sys, os
import subprocess

"""
showeeprom
"""
#source FIRSTCALL='YES'

args = len(sys.argv)
command = sys.argv[0].split("/")[-1]

if args == 1:
    path = os.path.join(os.sep,"root","HPE3PAR","CONF",command)
    with open(path) as f:
        print f.read()
#del os.environ['SYSD']
#os.unsetenv("SYSD")
#os.system('bash')
#sys.exit(0)
