#!/usr/bin/env python
"""
HOST --         showhost -d
                showhost
                showhost -persona
                showhost -chap
                showhost -agent
                showhost -pathsum
                showhost -listpersona				
                showhost -noname
                showhost -lesb
                showhost -domain *
                showhost -verbose
"""
import sys, os

args = len(sys.argv)
command = sys.argv[0].split("/")[-1]

if args == 1:
    path = os.path.join(os.sep,"root","HPE3PAR","CONF","Host",command)
    with open(path) as f:
        print f.read()
else:
    filename = command+"".join(sys.argv[1:])
    path = os.path.join(os.sep,"root","HPE3PAR","CONF","Host",filename)
    argument = sys.argv[1]
    try:
        with open(path) as f:
            print f.read()
    except:
        raise
