#!/usr/bin/env python
"""
Controller--    shownode
                                shownode -listcols
                                shownode -showcols Name,Node,State,Master,InCluster,Control_Mem,Data_Mem,Available_Cache
                                shownode -d

"""
import sys, os, re

args = len(sys.argv)
command = sys.argv[0].split("/")[-1]

if args == 1:
    path = os.path.join(os.sep,"root","HPE3PAR","CONF","ControllerNode",command)
    with open(path) as f:
        c= f.read()
    print re.sub(" \t\r\f\v" , ",", c)
    #print c.replace(" ", ",")
else:
    filename = command+"".join(sys.argv[1:])
    path = os.path.join(os.sep,"root","HPE3PAR","CONF","ControllerNode",filename)
    argument = sys.argv[1]
    try:
        with open(path) as f:
            print f.read()
    except:
        raise

