#!/usr/bin/env python
import sys, os
"""
showeeprom
"""
import re
from datetime import datetime
from pytz import timezone
fmt = "%Y-%m-%d %H:%M:%S %Z"
dt = "%Y-%m-%d"
t = "%H:%M:%S"

now_time = datetime.now(timezone('America/Chicago'))
cdttime =  now_time.strftime(fmt)
de =  now_time.strftime(dt)
t =  now_time.strftime(t)

args = len(sys.argv)
command = sys.argv[0].split("/")[-1]

def get_strptime(timestamp):
    date_format = "%Y-%m-%d %H:%M:%S"
    return (datetime.strptime(timestamp, date_format))

def get_time_diff(start_time, end_time):
    a = get_strptime(start_time)
    b = get_strptime(end_time)
    delta = b-a
    return delta

def add_new_time(new_time_list, end_time, diff_time):
    if new_time_list[-1]<end_time:
        new_list = []
        st = new_time_list[-1]
        for d in diff_time:
            st = str(get_strptime(st) + d)
            new_list.append(st)
    return new_list

def add_delta(d, tm, delta_time):
    return (get_strptime(d+" "+tm)+delta_time)

def update_cdt(contents, de, t):
    dates =  re.findall(r'[0-9]{4}-[0-9]{2}-[0-9]{2}', contents)
    date =  list(set(dates))[0]
    c = contents.replace(date,str(de))
    times =  re.findall(r'[0-9]{2}:[0-9]{2}:[0-9]{2}', contents)
    if len(list(set(times)))> 1:
         t1= get_strptime(de+" "+times[0])
         t2= get_strptime(de+" "+times[1])
         td = get_time_diff(de+" "+times[0], de+" "+times[1])
         new_td = td
         for i in range(len(times)):
             c= c.replace(times[i],str(add_delta(de, t,new_td)).split(" ")[1])
             new_td = td+new_td
         return c
    else:
         c = c.replace(times[0], t)
         return c


args = len(sys.argv)
command = sys.argv[0].split("/")[-1]

if args == 1:
    path = os.path.join(os.sep,"root","HPE3PAR","CONF",command)
    with open(path) as f:
        contents = f.read()
    print update_cdt(contents, de, t)
    #with open(path) as f:
        #print f.read()


