#!/usr/bin/env python
import sys, os
"""
CPG - srcpgspace -attime -groupby CPG_NAME
system -
	cpgspc - srcpgspace -btsecs -15m

"""

args = len(sys.argv)
command = 'cpgSapce.txt' 
arguments = sys.argv[1:]

if args == 1:
    #no arguments
    print "Not a valid command"
else:
    if '-btsecs' in arguments:
        path = os.path.join(os.sep,"root","HPE3PAR","PERF","system",command)
    elif 'CPG_NAME' in arguments:
        path = os.path.join(os.sep,"root","HPE3PAR","PERF","CPG",command)
    try:
        with open(path) as f:
            print f.read()
    except:
        raise

