#!/usr/bin/env python
import sys, os, time
"""
srstatcpu-attime-groupbynode
"""
import re
from datetime import datetime
from pytz import timezone
fmt = "%Y-%m-%d %H:%M:%S %Z"
dt = "%Y-%m-%d"
t = "%H:%M:%S"

now_time = datetime.now(timezone('America/Chicago'))
cdttime =  now_time.strftime(fmt)
de =  now_time.strftime(dt)
t =  now_time.strftime(t)

args = len(sys.argv)
command = sys.argv[0].split("/")[-1]

def get_epochtime(s=None):
    now_time = datetime.now(timezone('America/Chicago'))
    p = "%Y-%m-%d %H:%M:%S"
    if not s:
        s =  now_time.strftime(p)
    epoch = int(time.mktime(time.strptime(s, p)))+ 37800
    return epoch 


def get_strptime(timestamp):
    date_format = "%Y-%m-%d %H:%M:%S"
    return (datetime.strptime(timestamp, date_format))

def get_time_diff(start_time, end_time):
    a = get_strptime(start_time)
    b = get_strptime(end_time)
    delta = b-a
    return delta

def add_new_time(new_time_list, end_time, diff_time):
    if new_time_list[-1]<end_time:
        new_list = []
        st = new_time_list[-1]
        for d in diff_time:
            st = str(get_strptime(st) + d)
            new_list.append(st)
    return new_list

def add_delta(d, tm, delta_time):
    return (get_strptime(d+" "+tm)+delta_time)

def update_cdt(contents, de, t):
    dates =  re.findall(r'[0-9]{4}-[0-9]{2}-[0-9]{2}', contents)
    date =  list(set(dates))[0]
    c = contents.replace(date,str(de))
    times =  re.findall(r'[0-9]{2}:[0-9]{2}:[0-9]{2}', contents)
    epochs = re.findall(r'[0-9]{10}',contents)
    if len(list(set(times)))> 1:
         t1= get_strptime(de+" "+times[0])
         t2= get_strptime(de+" "+times[1])
         td = get_time_diff(de+" "+times[0], de+" "+times[1])
         new_td = td
         for i in range(len(times)):
             newts = add_delta(de, t,new_td)
             c= c.replace(times[i],str(newts).split(" ")[1])
             c= c.replace(epochs[i],str(get_epochtime(str(newts))))
             new_td = td+new_td
         return c
    else:
         c = c.replace(times[0], t)
         s = str(de+" "+t)
         new_epoch= str(get_epochtime(s))
         c = c.replace(epochs[0], new_epoch)
         return c

args = len(sys.argv)
command = sys.argv[0].split("/")[-1]

if args == 1:
    #no arguments
    path = os.path.join(os.sep,"root","HPE3PAR","PERF",command)
    with open(path) as f:
        print f.read()
else:
    if "-btsecs" in sys.argv:
        filename = command+"-btsecs"
        path = os.path.join(os.sep,"root","HPE3PAR","PERF",filename)
    else:
        filename = command+"".join(sys.argv[1:])
        path = os.path.join(os.sep,"root","HPE3PAR","PERF",filename)
        argument = sys.argv[1]
    try:
        with open(path) as f:
            contents = f.read()
        print update_cdt(contents, de, t)
    except:
        raise

